// <auto-generated />
using Catblog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catblog.Migrations
{
    [DbContext(typeof(AdminCatContext))]
    [Migration("20250929064632_Cat2")]
    partial class Cat2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catblog.Models.AdminCat", b =>
                {
                    b.Property<int>("AdminCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminCatId"));

                    b.Property<int>("AdminCatAge")
                        .HasColumnType("int");

                    b.Property<string>("AdminCatDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminCatGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminCatId1")
                        .HasColumnType("int");

                    b.Property<string>("AdminCatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminCatRate")
                        .HasColumnType("int");

                    b.Property<string>("AdminCatSpecies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminCatId");

                    b.HasIndex("AdminCatId1");

                    b.ToTable("adminCats");
                });

            modelBuilder.Entity("Catblog.Models.AdminCat", b =>
                {
                    b.HasOne("Catblog.Models.AdminCat", "adminCat")
                        .WithMany()
                        .HasForeignKey("AdminCatId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("adminCat");
                });
#pragma warning restore 612, 618
        }
    }
}
